/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.sql.*;
import Modelo.*;
import javax.swing.JOptionPane;
public class NewJFrame extends javax.swing.JFrame {

    Conexion conectar = Conexion.getInstance();
    
    public NewJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ver Receta");
        llenarCombo();
    }
    
    public void llenarCombo(){
        String []Datos = new String[1];
        String texto;
        
        try {
            Connection conexion = conectar.conectar();
            PreparedStatement buscar = conexion.prepareStatement("SELECT * FROM tortas");
            ResultSet consulta = buscar.executeQuery();
            
            while(consulta.next()){
                Datos[0] = consulta.getString(1);                
                texto = Datos[0];
                cbTorta.addItem(texto);
                
            }
            conectar.cerrarConexion();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cbTorta = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInf = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 226, 196, 88));

        cbTorta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar torta" }));
        getContentPane().add(cbTorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 66, 245, 50));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 66, 150, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInf.setColumns(20);
        txtInf.setRows(5);
        jScrollPane1.setViewportView(txtInf);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 390, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*txtInf.setText("");
        String id_torta = cbTorta.getSelectedItem().toString();
        Double cant = Double.parseDouble(txtCantidad.getText().trim()); 
        try {
            Connection conexion = conectar.conectar();
            PreparedStatement seleccionar = conexion.prepareStatement("SELECT nombre, cantidad * +cant+, unidad FROM Ingredientes WHERE id_torta = '\"+id_torta+\"';");            
            //PreparedStatement seleccionar = conexion.prepareStatement("SELECT nombre, cantidad, unidad FROM ingredientes where id_torta = '"+id_torta+"';"); 
            ResultSet consulta = seleccionar.executeQuery();
            
            while(consulta.next()){
                txtInf.append(consulta.getString(1));
                txtInf.append("   ");
                txtInf.append(consulta.getString(2));
                txtInf.append("   ");
                txtInf.append(consulta.getString(3));
                txtInf.append("   ");                
                txtInf.append("\n");                 
                
            }
            conectar.cerrarConexion();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : "+e);
        }*/
        txtInf.setText("");
        String id_torta = cbTorta.getSelectedItem().toString();
        Double cant = Double.parseDouble(txtCantidad.getText().trim());

        try {
            Connection conexion = conectar.conectar();
            PreparedStatement seleccionar = conexion.prepareStatement(
                    "SELECT nombre, cantidad * cant, unidad FROM Ingredientes WHERE id_torta = '\"+id_torta+\"' ;"
            );
            seleccionar.setDouble(3, cant);
            seleccionar.setString(5, id_torta);

            ResultSet consulta = seleccionar.executeQuery();

            while (consulta.next()) {
                txtInf.append(consulta.getString(1));
                txtInf.append("   ");
                txtInf.append(consulta.getString(2));
                txtInf.append("   ");
                txtInf.append(consulta.getString(3));
                txtInf.append("   ");
                txtInf.append("\n");
            }

            conectar.cerrarConexion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTorta;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtInf;
    // End of variables declaration//GEN-END:variables
}
